# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - idt-develop
    - idt-feature-LC-*
    - idt-release-v*
    - idt-hotfix-v*
  tags:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      jdkVersionOption: '1.8'
      javaHomeOption: 'JDKVersion'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: 'build/test-results/**/TEST-*.xml'
      tasks: 'build'
    displayName: 'Gradle build'

  - task: Docker@2
    inputs:
      containerRegistry: 'lpgregistry ACR'
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
        repository: 'notification-service/prod'
      ${{ else }}:
        repository: 'notification-service/test'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.SourceBranchName)'