server:
  port: 9006

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    org.apache.http: WARN

govNotify:
  key: ${GOV_NOTIFY_API_KEY:key}

oauth:
  serviceUrl: ${OAUTH_SERVICE_URL:http://localhost:8080}
  clientId: ${CLIENT_ID:9fbd4ae2-2db3-44c7-9544-88e80255b56e}
  clientSecret: ${CLIENT_SECRET:test}
  checkTokenUrl: "${oauth.serviceUrl}/oauth/check_token"
  tokenUrl: "${oauth.serviceUrl}/oauth/token"
  jwtKey: ${jwt_key}

